### ISSUE TITLE
Deprecation warning on Ubuntu 16.04

### ISSUE THREAD

**Issue by cinhtau** [netlify/jekyll-srcset#8]
I use Ubuntu 16.04. With use of this plugin jekyll gives a deprecation warning.

`[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead`

**Comment by Danny4927** [comment]
Hey i have the same issue on arch linux. I think its the `require "RMagick"` line in [ jekyll-srcset/lib/jekyll/srcset/tag.rb](https://github.com/netlify/jekyll-srcset/blob/master/lib/jekyll/srcset/tag.rb). I think it could be simply changed to require "rmagick"

**Comment by cinhtau** [comment]
@Danny4927 I have disbanded the use of this plugin. I have written with gulp a responsive image generator, that does it for me. I am fine if the maintainers want to close this issue.
